[package]
name = "windivert"
version = "0.1.0"
authors = ["ray851107 <ray851107@gmail.com>"]

[dependencies]
winapi = "*"
kernel32-sys = "*"
windivert-sys = { version = "*", path = "../windivert-sys" }